"""The nine-day journey, with only recorded times shown as actual times."""
def apply(DAYS):
 def setday(n,**kw):DAYS[n-1].update(kw)
 setday(1,summary='晚間抵達 Anchorage → 飯店休息',intro='晚上抵達 Anchorage，入住 Anchorage 飯店。第一晚沒有另外安排活動，為隔天清晨的火車與遊船保留體力。',rows=[('晚間','旅程紀錄','抵達 Anchorage、入住','抵達後前往飯店休息，隔天一早出發。','')])
 setday(2,summary='06:45 火車 → 11:20 Seward → 12:00 遊船 → 18:00 火車 → 22:15 Anchorage',rows=[('06:45–11:20','搭乘紀錄','Coastal Classic：Anchorage → Seward','搭火車沿海岸與山谷南下。火車與 5.5 小時遊船透過 Alaska Railroad 搭配安排。','coastal'),('11:20–11:35 左右','接駁紀錄','車站 → 船公司接駁 → 小船碼頭','下車後直接搭船公司接駁，約 11:35 到櫃檯辦理 check-in。',''),('登船前空檔','親身經驗','Kenai Fjords 遊客中心快訪','完成報到後曾快訪遊客中心，來回約十分鐘，非常趕。先確認登船期限再決定是否前往。','center'),('12:00–17:30','搭乘紀錄','Kenai Fjords 冰川與峽灣遊船','5.5 小時海上行程，看冰川、峽灣與野生動物；回港後接續車站接駁。','cruise'),('回港後','接駁紀錄','碼頭 → Seward 車站','當時安排約 17:50 前搭車回站，銜接 18:00 火車。不要假定列車會等遲到旅客。',''),('18:00–22:15','搭乘紀錄','Coastal Classic：Seward → Anchorage','晚班火車回城，當晚仍住 Anchorage。','coastal')])
 setday(3,summary='07:45 報到 → 08:20 火車 → 15:40 抵達 → 入住 → 約 18:00 Fly Denali 冰川飛行',rows=[('07:45 左右','旅程紀錄','Anchorage 車站報到','這次的到站時間較接近發車；後續旅客應依鐵路規定預留完整報到時間。','rail'),('08:20–15:40','搭乘紀錄','Denali Star：Anchorage → Denali','景觀列車北上，火車本身也是旅行的一部分。','denali-rail'),('15:55–16:15 左右','接駁紀錄','專屬接駁 → Denali 園區入口飯店','從車站搭飯店接駁，抵達後辦理入住。',''),('17:30 左右','接駁紀錄','Fly Denali 飯店接送 → Healy','業者派車接往飛行基地，準備傍晚冰川飛行與著陸；帶上太陽眼鏡。','flight'),('18:00 左右','親身經驗','Fly Denali 冰川飛行','小飛機看山系與 Ruth Glacier，這項體驗非常推薦。飛行與著陸仍視天候決定。','flight'),('20:00 左右','接駁紀錄','回飯店、晚餐','搭回程接駁回住宿，再在飯店用餐。','')])
 setday(4,intro='當次 Tundra Wilderness Tour 是 06:00 飯店接送。營運季每天有團、需要提前報名，實際時刻在出發前 48 小時公布；以下是這次的活動順序。',rows=[('06:00','搭乘紀錄','Tundra Wilderness Tour 飯店接送','從 Denali 園區入口飯店 出發，搭巴士深入公園。規劃此活動通常需留約 5–5.5 小時，依當次團隊安排為準。','bus'),('中午','旅程紀錄','Denali Visitor Center、午餐','回入口區用餐，再準備下午犬舍接駁。','center'),('14:00 場次','旅程紀錄','Sled Dog Demonstration','從遊客中心搭 Sled Dog Shuttle 去犬舍，提前排隊，觀賞雪橇犬示範。','dogs'),('下午','旅程紀錄','Savage River 河谷短走','搭園區接駁到河谷，依回程班次與晚餐活動時間決定步行長度。','savage'),('19:00 多的場次','親身經驗','Cabin Nite 晚餐劇場','這次另加的晚餐與表演，很有趣；實際報到和接送以訂位通知為準。','cabin')])
 setday(5,summary='09:30 退房 → 10:00 遊客中心 → 12:30 火車 → 20:00 Anchorage',rows=[('09:30 左右','旅程紀錄','退房、行李寄放與車站交接','向飯店確認行李送往火車站的安排，再出發去遊客中心。',''),('10:00 左右','旅程紀錄','Denali Visitor Center','看展、蓋章及入口區活動，為中午火車留出回站時間。','center'),('12:00 左右','旅程紀錄','Denali 車站報到','確認行李交接與上車位置；後續旅客依車票規定提前到站。','rail'),('12:30–20:00','搭乘紀錄','Denali Star：Denali → Anchorage','搭南下列車回城，入住 Anchorage，確認隔天 Katmai 接送。','denali-rail')])
 setday(6,title='Katmai 第一次出發｜天氣折返、Anchorage 市區',summary='飯店接送 → Katmai Air 起飛後折返 → 下午改走 Anchorage',intro='原本預訂 Katmai Air 經 King Salmon 前往 Brooks Camp；當天起飛後因天氣與低能見度原機返回 Anchorage。下午改成市區活動，同時聯絡其他飛行業者找隔天空位。',rows=[('早上','旅程紀錄','飯店接駁 → Katmai Air 出發','原訂 08:00 Anchorage → King Salmon，10:00 再前往 Brooks Camp。當天未能完成這段航程。','arrival'),('起飛後','旅程紀錄','因天氣返回 Anchorage','原機折返，這天沒有到 Brooks Camp。業者當時可退款，但後面班次幾乎全滿。','backup'),('下午','旅程紀錄','Alaska Public Lands Information Center','改到市區了解公共土地、詢問 NPS 資訊及蓋章。','anchorage-center'),('下午','旅程紀錄','Ship Creek／William Jack Hernandez Hatchery','市區看鮭魚、用餐與休息，同時找其他 air taxi 的空位。','ship-creek')],notes=[])
 setday(7,title='Katmai 成功看熊｜Brooks Camp → Copper Center',page='parks/katmai/',sleep='Copper Center',summary='早上換業者進 Brooks Camp → 看熊 → 17:00 多回 Anchorage → 租車往 Copper Center',intro='臨時找到另一家業者，隔天成功進入 Brooks Camp。看熊結束後回 Anchorage 取車，再往 Copper Center 移動；這是整趟最緊湊的一天。',rows=[('早上','搭乘紀錄','小飛機前往 Brooks Camp','第二家業者的精確起飛與轉乘時刻未留存，不套用前一天 Katmai Air 的班表。','arrival'),('抵達後','旅程紀錄','Bear School、寄存食物','先完成熊安全說明，存放食物與有氣味用品，再開始看熊。','arrival'),('園內活動','親身經驗','Lower River → Brooks Falls Trail → Riffles → 瀑布平台','先看 Lower River，問 ranger 熊在哪裡，再往瀑布；回程再看 Lower River。不只守在一個平台。','route'),('用餐休息','親身經驗','自備簡單食物、不吃 buffet','在指定用餐區進食，把更多時間留給熊。當次保守估計看到約五隻不同的熊，包括母子與吃鮭魚的熊。',''),('17:00 多','搭乘紀錄','回到 Anchorage','搭機回城後前往機場租車，接續公路段。','backup'),('晚間','旅程紀錄','租車 → Copper Center 入住','取車後沿 Glenn Highway 前往 Copper Center。沒有精確抵達時間紀錄；若返程延誤或疲累，應調整住宿與公路段。','road')],notes=[])
 setday(8,summary='Copper Center 遊客中心與短步道 → Matanuska 觀景健行 → Anchorage',intro='從 Copper Center 出發，參觀國家公園遊客中心、蓋章、看展和走短步道；之後沿 Glenn Highway 返回 Anchorage，途中停 Matanuska 州立休憩區健行。',rows=[('上午','旅程紀錄','Wrangell–St. Elias Visitor Center','看展、蓋章及遊客中心附近短步道，認識 Copper Center 入口區；這次沒有深入 McCarthy／Kennecott。','center'),('返程途中','旅程紀錄','Glenn Highway → Matanuska 州立休憩區','沿公路西行，在回城途中停下來短走、看冰川景觀。','road'),('下午','親身經驗','Matanuska Glacier State Recreation Site 健行','沿森林步道到冰川觀景位置，當時還遇到野生 moose。這裡可以遠眺冰川，不能從此走上冰面。','matanuska'),('之後','旅程紀錄','返回 Anchorage','回到 Anchorage 住宿，隔天整理行李、還車與返程。','')])
 setday(9,summary='整理行李 → 退房 → 還車 → 機場返程',intro='最後一天整理行李、退房與還車，再前往機場離開 Anchorage。',rows=[('返程日','旅程紀錄','收行李、退房與還車','依返程班機安排出門時間，為租車場到航廈的移動與報到留餘裕。','')])
